language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
  - '10'
before_install:
- npm install -g npm5
- npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm prune
after_script:
  greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/


